### ISSUE TITLE
Fail to build an installation package: Android environment setting up missing

### ISSUE THREAD

**Issue by andiechu** [overhandtech/alpine-node-build#3]
When I ran ionic build to build a .pkg installation package (using /docker/Dockerfile.android file), it gives me exceptions like this: 

> [cordova]  No scripts found for hook "after_prepare".
> [cordova]  Failed to find 'ANDROID_HOME' environment variable. Try setting it manually.
> [cordova]  Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
> [cordova]  CordovaError: Failed to find 'ANDROID_HOME' environment variable. Try setting it manually.
> [cordova]  Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
> [cordova]      at /usr/src/app/platforms/android/cordova/lib/check_reqs.js:297:19
> [cordova]      at _fulfilled (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:834:54)
> [cordova]      at /usr/src/app/platforms/android/cordova/node_modules/q/q.js:863:30
> [cordova]      at Promise.promise.promiseDispatch (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:796:13)
> [cordova]      at /usr/src/app/platforms/android/cordova/node_modules/q/q.js:857:14
> [cordova]      at runSingle (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:137:13)
> [cordova]      at flush (/usr/src/app/platforms/android/cordova/node_modules/q/q.js:125:13)
> [cordova]      at process._tickCallback (internal/process/next_tick.js:61:11)

Seems like there are some env missing in the image.

**Comment by andiechu** [comment]
@rngadam @xuyuji9000
